# Autogenerated wrapper script for GAP_pkg_ferret_jll for powerpc64le-linux-gnu-cxx03
export ferret

using GAP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_ferret")
JLLWrappers.@declare_file_product(ferret)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll)
    JLLWrappers.@init_file_product(
        ferret,
        "lib/gap/ferret.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
